DATA ENCODING

There are several techniques for data encoding:

1. Nominal or One Hot Encoding
2. Label or Ordinal Encoding
3. Target Guided Ordinal Encoding

Nominal /OHE should not be used when the data has a lot of categories

In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [ ]:
## create a simple dataframe
df=pd.DataFrame({
    'color':['red','blue','green','green','red','blue']
})

In [3]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [4]:
## create an instance of OneHotEncoder
encoder=OneHotEncoder()

In [6]:
## perform fit and transform
encoded=encoder.fit_transform(df[['color']]).toarray()

In [7]:
encoder_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [8]:
encoder_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [10]:
## for new data
encoder.transform([['blue']]).toarray()

c:\code files\code\penv\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

In [12]:
pd.concat([df,encoder_df],axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5   blue         1.0          0.0        0.0

LABEL ENCODING

the problem with label encoding is that the system can think that red>green>blue due to the numbers assigned

In [13]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [15]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder=LabelEncoder()

In [16]:
lbl_encoder.fit_transform(df[['color']])

c:\code files\code\penv\lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 1, 2, 0])

In [17]:
lbl_encoder.transform([['green']])

c:\code files\code\penv\lib\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([1])

ORDINAL ENCODING

If you have a use case where you need to assign ranks to categories, you can use ordinal encoding. Ordinal encoding is used to encode categorical data that have an intrinsic order or ranking. Each category is assigned a numerical value based on its position in the order.

High school : 1
College : 2
graduate : 3
Post graduate : 4

In [21]:
from sklearn.preprocessing import OrdinalEncoder
df1=pd.DataFrame({
    'size': ['small', 'medium', 'large', 'medium', 'small', 'large']
})

In [22]:
df1

     size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [23]:
encoder = OrdinalEncoder(categories=[['small', 'medium', 'large']])

In [25]:
encoder.fit_transform(df1[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [26]:
encoder.transform([['small']])

c:\code files\code\penv\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[0.]])

TARGET GUIDED ORDINAL ENCODING

Target guided ordinal encoding is particularly useful when dealing with categorical variables that have a large number of unique categories. The core idea is to replace each category in the categorical variable with a numerical value derived from the mean or median of the target variable for that category.

In [27]:
## create a simple dataframe with a categorical variable and a target variable
df2=pd.DataFrame({
    'city' : ['newyork', 'london', 'paris', 'tokyo', 'newyork', 'paris'],
    'price' : [200, 150, 300, 250, 180, 320]
})

In [28]:
df2

      city  price
0  newyork    200
1   london    150
2    paris    300
3    tokyo    250
4  newyork    180
5    paris    320

In [33]:
mean_price=df2.groupby('city')['price'].mean().to_dict()

In [34]:
mean_price

{'london': 150.0, 'newyork': 190.0, 'paris': 310.0, 'tokyo': 250.0}

In [39]:
df2['city_encoded'] = df2['city'].map(mean_price)

In [40]:
df2

      city  price  city_encoded
0  newyork    200         190.0
1   london    150         150.0
2    paris    300         310.0
3    tokyo    250         250.0
4  newyork    180         190.0
5    paris    320         310.0